l_spanish:
 DIVISION_QUEUED:0 "$N$ División"
 DIVISIONS_QUEUED:0 "$N$ Divisiones"
 CONVEYOR_EQUIPMENT_NEED:0 "Necesidad de equipo:"
 CONVEYOR_MANPOWER_NEED:0 "Necesidad de mano de obra: $AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL:0 "División"
 DEPLOYMENT_PROGRESS_LABEL:0 "Progreso"
 DEPLOYMENT_PRIORITY_LABEL:0 "Prioridad"
 DEPLOYMENT_DEPLOY_LABEL:0 "Desplegar"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§GHaz clic para agregar a la cola de despliegue§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§GHaz clic para copiar a nuestras plantillas desplegables§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§GHaz clic para editar la plantilla de división§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§GHaz clic para ver la plantilla de división§!"
 DEPLOYMENT_TRAINING:0 "Entrenamiento: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ ( La experiencia máxima de despliegue depende de la cantidad de equipo )"
 DEPLOYMENT_CURRENT_LEVEL:0 "El nivel actual de despliegue es $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_MANPOWER_DESC:0 "Mano de obra: $VALUE|Y0$ ( Máx $MAX|Y0$ )"
 DEPLOYMENT_EXPERIENCE_DESC:0 "\nSi el entrenamiento se completa, esta unidad ganará suficiente experiencia para ser desplegada como nivel $NUMBER$ ( $MAXLEVEL|%Y0$ ) dándole un modificador de combate de $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\n Si esta unidad está completamente equipada, el entrenamiento finalizará el §Y$DATE$§!"
 DEPLOYMENT_EQUIPMENT:0 "Equipo: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER:0 "Diseñador de Divisiones"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_ADD_TEMPLATE:0 "Entrenar"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "Podemos entrenar un máximo de $CAP|*H$ hombres.\nLimitado por la mano de obra máxima en el campo ( $RATIO|H0%$ de $INFIELD|*H$. Mínimo: $MINPOSSIBLE|*H$ hombres)"
 DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP:0 "§RSe alcanzó el límite para esta plantilla§! \n"
 REGIMENTS_SELECTION_CANCEL:0 "Atrás"
 ONLY_ONE_TEMPLATE_LEFT:0 "No puedes eliminar tu última plantilla."
 DELETE_TEMPLATE:0 "§REliminar§! plantilla de la lista."
 DELETE_TEMPLATE_TITLE:0 "Eliminar plantilla"
 DELETE_TEMPLATE_DESC:0 "¿Estás seguro de que deseas eliminar esta plantilla?"
 DEPLOYMENT_REMOVE_DIVISION:0 "Cancelar división"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "Reclutar y desplegar"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "No se puede §RDesplegar§! una unidad que no tiene equipo.\nPor favor, espera hasta que este despliegue reciba algún equipo."
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "No se puede §RDesplegar§! una unidad que no tiene hombres."
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "No se puede §RDesplegar§! una unidad que no esté al menos $VALUE|1H%$ entrenada (Actual $CURRENT|1R%$)"
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "No se puede §RDesplegar§! una unidad que nos pondría por encima del límite de fuerzas especiales"
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP:0 "No se puede §RDesplegar§! una unidad que nos pondría por encima del límite de plantilla de la división"
 DEPLOYMENT_HOW_TO_DESC:0 "Selecciona el(los) despliegue(s) de la lista y luego §Ghaz clic§! en las provincias resaltadas en el mapa para desplegar.\n§gLas unidades desplegadas con equipo incompleto lo obtendrán a través de las solicitudes de refuerzo.\nConsidera que las unidades desplegadas demasiado pronto no recibirán el entrenamiento adecuado.§!"
 OPERATIONS_DESC:1 "§YOperaciones§!\n§TEstablecer prioridad para el equipo destinado a la preparación y ejecución de operaciones§!"
 OPERATIONS_EMPTY:0 "§GNo hay solicitudes actuales para operaciones.§!"
 REINFORCEMENT:0 "Refuerzos"
 REINFORCEMENT_DESC:1 "§YRefuerzos§!\n§TEstablecer prioridad para el equipo destinado a reforzar tropas activas en comparación con la cola de despliegue y las mejoras§!"
 REINFORCEMENT_EMPTY:0 "§GNo hay solicitudes actuales para equipo.§!"
 UPGRADES:0 "Mejoras"
 UPGRADES_DESC:1 "§YMejoras§!\n§TEstablecer prioridad para el equipo destinado a mejorar tropas activas en comparación con la cola de despliegue y los refuerzos§!"
 UPGRADES_EMPTY:0 "§GNo hay solicitudes actuales para mejoras.§!"
 group_infantry_title:0 "Regimiento de Infantería"
 group_artillery_title:0 "Regimiento de Artillería"
 group_mobile_title:0 "Regimiento Móvil"
 group_armor_title:0 "Regimiento Acorazado"
 group_support_title:1 "Compañías de Apoyo"
 NEW_GROUP_ADDITIONAL_COST:0 "Nuevo grupo $VALUE|H0$£army_experience£"
 GARRISONS:0 "Guarniciones"
 GARRISONS_DESC:0 "§TEstablecer prioridad para el equipo destinado a guarniciones§!"
 GARRISONS_DESC:1 "§YGuarniciones§!\n§TEstablecer prioridad para el equipo destinado a guarniciones§!"
 GARRISONS_EMPTY:0 "§GNo hay solicitudes actuales para guarniciones.§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$ contra $COUNTRY$"
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ contra $COUNTRY|H$"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§TEstablecer prioridad para el equipo que apoyará esta actividad diplomática.§!"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§GSe recolectó la máxima cantidad de equipo.§!"
 LAND_DEPLOYMENT:0 "§TDespliegue en Tierra§!"
 AIR_DEPLOYMENT:0 "§TDespliegue Aéreo§!"
 NAVAL_DEPLOYMENT:0 "§TDespliegue Naval§!"
 DIVISION_DESIGNER_RENAME:0 "Renombrar"
 DIVISION_DESIGNER_UPDATE:0 "Actualizar"
 DEPLOY:0 "Desplegar"
 EDIT:0 "Editar"
 VIEW:0 "Ver"
 COPY:0 "Copiar"
 DIVISION_EQUIPMENT:1 "Equipo"
 NEW_EQUIPMENT_ALLOWED:0 "Usar nuevo equipo"
 DO_NOT_CONTAINS_TEMPLATE:0 "§RNo se puede eliminar esta plantilla. El país no contiene esta plantilla.§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§RNo se puede eliminar esta plantilla porque $AMOUNT|H$ División(es) la están usando.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§RNo se puede eliminar esta plantilla porque $AMOUNT|H$ División(es) están en transición de esta plantilla a una nueva (Esperando recibir equipo que coincida con la nueva plantilla).§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "No se puede §REliminar§! esta plantilla del país. El país tiene $AMOUNT|H$ despliegues usando esta plantilla."
 HAS_GARRISON_WITH_TEMPLATE:0 "§RNo se puede eliminar esta plantilla porque se está utilizando como plantilla de guarnición en algunos territorios ocupados.§!"
 DEPLOYMENT_TEMPLATE_LABEL:0 "Plantillas"
 TEMPLATE_PRIO_0:0 "Reservas"
 TEMPLATE_PRIO_0_DESC:0 "Las unidades con esta plantilla recibirán equipo al último y con la prioridad más baja una vez desplegadas. Perfecto para unidades destinadas a proteger bases y similares."
 TEMPLATE_PRIO_1:0 "Predeterminado"
 TEMPLATE_PRIO_1_DESC:0 "Las unidades con esta plantilla recibirán prioridad media para equipo y refuerzos una vez desplegadas."
 TEMPLATE_PRIO_2:0 "Élite"
 TEMPLATE_PRIO_2_DESC:0 "Las unidades con esta plantilla recibirán equipo antes que las demás una vez desplegadas y con la mayor prioridad. Úsalas para tus mejores hombres y donde puedan ser más útiles."
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "Préstamo y arriendo: $COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "Añadir unidad"
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "Añade otra unidad de $CONVEYOR|H$ para ser producida en paralelo.\n\n§GShift+Clic§! para añadir 5 líneas"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "Escriba aquí para cambiar el nombre genérico de la línea de despliegue."
 CONVEYOR_TEMPLATE_ICON_DESC:0 "Este despliegue crea divisiones utilizando la plantilla $TEMPLATE|H$."
 CANCEL_CONVEYOR_TOOLTIP:0 "§RCancelar§! la producción de todas las líneas de despliegue."
 DEPLOY_CONVEYOR_TOOLTIP:0 "§GClic§! para desplegar todas las líneas instantáneamente."
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "No tiene ningún despliegue listo para §RDesplegar§!."
 CONVEYOR_CANCEL_TITLE:0 "§RCancelar§! Producción"
 CONVEYOR_CANCEL_DESC:0 "¿Está seguro de que desea §RCancelar§! la producción de todas las líneas de despliegue?"
 CONVEYOR_LINE_CANCEL_DESC:0 "§RCancelar§! la producción de esta línea."
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "§RCancelar§! línea de despliegue"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "¿Está seguro de que desea §RCancelar§! la producción de esta línea de despliegue?\n(El despliegue también será §REliminado§!)"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "¿Está seguro de que desea §RCancelar§! la producción de esta línea de despliegue?"
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§GClic§! para asignar el despliegue a la orden.\n§GClic derecho§! para restablecer la asignación de la orden."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "El despliegue debe tener al menos una orden dentro del teatro para ser asignado a cualquier grupo."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "El despliegue debe tener una ubicación objetivo para ser asignado a cualquier grupo."
 CONVEYOR_SET_LOCATION_DESC:0 "§GClic§! para establecer la ubicación de despliegue para este despliegue.\n§GClic derecho§! para restablecer la ubicación."
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§GClic§! para establecer la ubicación de despliegue para este despliegue.\n§GClic derecho§! para restablecer la ubicación.\n§YEsta es una plantilla colonial y solo puede desplegarse en el país de origen!§!"
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§RNo se ha establecido ubicación§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "Escriba aquí para cambiar el prefijo de la línea actual."
 CONVEYOR_LINE_DEPLOY_DESC:0 "§GClic§! para desplegar esta línea instantáneamente."
 CONVEYOR_SERIES_INCREASE_DESC:0 "Aumenta el número de entrenamientos en serie de divisiones que completará cada línea.\n\nEstablecerlo en infinito significa que cada línea entrenará una nueva división cuando se despliegue la anterior."
 CONVEYOR_SERIES_AMOUNT_DESC:0 "Este es el número de divisiones que entrenará cada línea antes de ser eliminada.\n\nEstablecerlo en infinito significa que cada línea entrenará una nueva división cuando se despliegue la anterior."
 CONVEYOR_SERIES_DECREASE_DESC:0 "Disminuye el número de entrenamientos en serie de divisiones que completará cada línea.\n\nEstablecerlo en infinito significa que cada línea entrenará una nueva división cuando se despliegue la anterior."
 CONVEYOR_LOW_PRIORITY_DESC:0 "Prioridad baja para refuerzos"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "Prioridad media para refuerzos"
 CONVEYOR_HIGH_PRIORITY_DESC:0 "Prioridad de refuerzo alta"
 CONVEYOR_CAN_NOT_TRAIN:0 "§RNo hay suficiente equipo para entrenar§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§RNo hay suficiente mano de obra para entrenar§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§RNo hay suficiente mano de obra o equipo para entrenar $DIVS|H$ de las divisiones§!"
 CONVEYOR_COLLAPSE_DESC:0 "§GHaz clic§! para colapsar"
 CONVEYOR_EXPAND_DESC:0 "§GHaz clic§! para expandir"
 CONVEYOR_MOVE_UP:0 "§GHaz clic§! para mover hacia arriba\n§GHaz Shift+Click§! para mover al inicio"
 CONVEYOR_MOVE_DOWN:0 "§GHaz clic§! para mover hacia abajo\n§GHaz Shift+Click§! para mover al final"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "Prioridad de equipo baja"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "Prioridad de equipo media"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "Prioridad de equipo alta"
 CONVEYOR_HAS_BAD_LOCATION:0 "La ubicación objetivo es §RInválida§! para el despliegue ahora."
 CONVEYOR_TRAINING_NOT_FINISHED:0 "El entrenamiento de esta línea aún no ha terminado."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "Número de serie actual de despliegue en la línea."
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§HErase el nombre personalizado.§!\nIntentará restaurar el nombre asignado originalmente, a menos que ya esté en uso."
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§HElige otro nombre histórico.§!\n§GHaz clic§! para abrir una lista de todos los nombres históricos aún disponibles. Es posible cambiar el grupo de los nombres editando la plantilla."
 DEPLOYMENT_LINE_EDIT_NAME:0 "§GHaz clic§! y escribe, para usar un nombre personalizado."
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§gSin nombres históricos disponibles.§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§RNo hay suficiente límite de fuerzas especiales§!"
 EXCEEDING_DIVISION_CAP:0 "§RExcediendo el límite para la plantilla de división§!"
 TRAINING_HALTED:0 "El entrenamiento ha sido detenido\n"
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "No se pueden eliminar plantillas especiales."
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "No se puede entrenar una nueva división de plantilla especial."
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "Como §HGobierno en el Exilio§! debemos controlar una §HCapital§! para entrenar nuevas divisiones."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "No se puede cambiar a esta plantilla porque eso causaría que excedamos nuestro límite de fuerzas especiales."
 CANT_CHANGE_DUE_TO_DIVISION_CAP:0 "No se puede cambiar a esta plantilla porque eso causaría que excedamos nuestro límite de divisiones."
 NO_SPECIAL_FORCES:0 "Esta plantilla no contiene ninguna fuerza especial."
 SPECIAL_FORCES_IN_TEMPLATE:1 "Esta plantilla contiene $NUM|Y$ batallones de fuerzas especiales."
 SPECIAL_FORCES_CAP_DESC:0 "Actualmente estás utilizando $USED|Y$ y entrenando $IN_TRAINING|Y$ de nuestros $CAP|Y$ batallones de fuerzas especiales permitidos."
 SPECIAL_FORCES_CAP_LIMIT_DESC:0 "Esta división está utilizando el límite de fuerzas especiales, porque ese es el límite más bajo."
 DIVISION_CAP_OF_TEMPLATE:0 "Esta plantilla tiene un límite de $NUM|Y$."
 DIVISION_CAP_USAGE_DESC:0 "Actualmente estás utilizando $USED|Y$ y entrenando $IN_TRAINING|Y$ de nuestras $CAP|Y$ divisiones permitidas para $NAME|Y$."
 DIVISION_CAP_LIMIT_DESC:0 "Esta división está utilizando el límite de plantilla, porque ese es el límite más bajo."
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "Esto deja espacio para $TRAINABLE|Y$ división(es) usando esta plantilla."
 SHOW_DECOMMISSIONED_TEMPLATES:0 "Mostrar §Hplantillas descomisionadas§!"
 DECOMMISSION_TEMPLATE_TOGGLE_ON:0 "Descomisionar"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC:0 "§GHaz clic§! para descomisionar esta plantilla, marcándola como retirada."
 DECOMMISSION_TEMPLATE_TOGGLE_OFF:0 "Recomisionar"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC:0 "§GHaz clic§! para recomisionar esta plantilla, marcándola como en servicio."
